### ISSUE TITLE
Unable to build Mitsuba ellipsoids branch

### ISSUE THREAD

**Issue by kidintwo3** [facebookresearch/volumetric_primitives#1]
CMake build fails on windows

**Comment by kidintwo3** [comment]
Is there a commit that is stable enough to test the code?

**Comment by Speierers** [comment]
Hi @kidintwo3 ,

Could you please provide config information about your system as well as a full detailed compilation log with the error message?

Thanks

**Comment by jiayaozhang** [comment]
Hi i have installed compile the [mitsuba3-ellispoids_release](https://github.com/mitsuba-renderer/mitsuba3/tree/ellipsoids_release)  successfully by following this [Mitsuba3 Compiling Guideline](https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html)

```
PS D:\volumetric_primitives\mitsuba3\build\Debug> mitsuba -h                                 

Mitsuba version 3.6.4 (ellipsoids_release[3ade6d83], Windows, 64bit, 32 threads, 8-wide SIMD)                           
Copyright 2024, Realistic Graphics Lab, EPFL                                                                            
Enabled processor features: cuda llvm avx2 avx fma f16c sse4.2 x86_64                                                   
                                                                                                                        
Usage: mitsuba [options] <One or more scene XML files>                                                                  
                                                                                                                        
Options:                                                                                                                
                                                                                                                        
    -h, --help                                                                                                          
        Display this help text.                                                                                         
                                                                                                                        
    -m, --mode                                                                                                          
        Request a specific mode/variant of the renderer                                                                 
                                                
```


but still encounter this error.

```
(volprim) D:\volumetric_primitives>python examples/optimize_volume.py --output output_tomo --volume_grid resources/smoke.vol --cam_count 4 --cam_res 128                                                             
Rendering reference images:                                                                                             
-- 4/4                                                                                                                  
Traceback (most recent call last):                                                                                      
  File "D:\volumetric_primitives\examples\optimize_volume.py", line 160, in <module>         
    scene = mi.load_dict(scene_dict)                                                                                    
            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                    
RuntimeError: ​[PluginManager] Plugin "ellipsoidsmesh" not found!                                                       
                                                                       
```

Can you help me?

I am using windows, cuda 4070ti

**Comment by tlxhlll** [comment]
> Hi i have installed compile the [mitsuba3-ellispoids_release](https://github.com/mitsuba-renderer/mitsuba3/tree/ellipsoids_release) successfully by following this [Mitsuba3 Compiling Guideline](https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html)
> 
> ```
> PS D:\volumetric_primitives\mitsuba3\build\Debug> mitsuba -h                                 
> 
> Mitsuba version 3.6.4 (ellipsoids_release[3ade6d83], Windows, 64bit, 32 threads, 8-wide SIMD)                           
> Copyright 2024, Realistic Graphics Lab, EPFL                                                                            
> Enabled processor features: cuda llvm avx2 avx fma f16c sse4.2 x86_64                                                   
>                              s                                                                                            
> Usage: mitsuba [options] <One or more scene XML files>                                                                  
>                                                                                                                         
> Options:                                                                                                                
>                                                                                                                         
>     -h, --help                                                                                                          
>         Display this help text.                                                                                         
>                                                                                                                         
>     -m, --mode                                                                                                          
>         Request a specific mode/variant of the renderer                                                                 
>                                                 
> ```
> 
> but still encounter this error.
> 
> ```
> (volprim) D:\volumetric_primitives>python examples/optimize_volume.py --output output_tomo --volume_grid resources/smoke.vol --cam_count 4 --cam_res 128                                                             
> Rendering reference images:                                                                                             
> -- 4/4                                                                                                                  
> Traceback (most recent call last):                                                                                      
>   File "D:\volumetric_primitives\examples\optimize_volume.py", line 160, in <module>         
>     scene = mi.load_dict(scene_dict)                                                                                    
>             ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                    
> RuntimeError: ​[PluginManager] Plugin "ellipsoidsmesh" not found!                                                       
>                                                                        
> ```
> 
> Can you help me?
> 
> I am using windows, cuda 4070ti

I have addressed this problem by compiling the branch of master, they have merged ellipsoids branch to master branch

**Comment by jiayaozhang** [comment]
Thanks for your, i try to compile the branch of master, but still encounter the error 

`RuntimeError: ​[PluginManager] Plugin "ellipsoidsmesh" not found!`

what do you mean in a different issue chat?

`Please don't run pip install mitsuba directly, this can not work.`

**Comment by tlxhlll** [comment]
> Thanks for your, i try to compile the branch of master, but still encounter the error 
> 
> `RuntimeError: ​[PluginManager] Plugin "ellipsoidsmesh" not found!`
> 
> what do you mean in a different issue chat?
> 
> `Please don't run pip install mitsuba directly, this can not work.`
> 
> 
> 

Maybe you can find a setpath.sh(maybe) in mitsuba3/build, then run source setpath.sh

**Comment by tlxhlll** [comment]
![Image](https://github.com/user-attachments/assets/8e1bd617-0e7a-4b35-83f4-c1087fb84786)

**Comment by jiayaozhang** [comment]
Thanks it really solve the problem for `​[PluginManager] Plugin "ellipsoidsmesh" not found!` perfectly

but i encounter some drjit problem for differential scene when compile the render_volume.py

```bash
  File "D:\mitsuba3\build\Release\python\drjit\opt.py", line 246, in __setitem__
    self._reset(key, value)
  File "D:\mitsuba3\build\Release\python\drjit\opt.py", line 474, in _reset
    raise Exception(f"Optimizer._reset({key}, {value}): missing implementation!")
Exception: Optimizer._reset(centers, [[-1, -1, -1],
 [-1, -1, -0.875],
 [-1, -1, -0.75],
 .. 4090 skipped ..,
 [0.875, 0.875, 0.625],
 [0.875, 0.875, 0.75],
 [0.875, 0.875, 0.875]]): missing implementation!

```
this issue trigger both in ubuntu and windows

**Comment by laiwei0304** [comment]
> Thanks it really solve the problem for perfectly`​[PluginManager] Plugin "ellipsoidsmesh" not found!`
> 
> but i encounter some drjit problem for differential scene when compile the render_volume.py
> 
>   File "D:\mitsuba3\build\Release\python\drjit\opt.py", line 246, in __setitem__
>     self._reset(key, value)
>   File "D:\mitsuba3\build\Release\python\drjit\opt.py", line 474, in _reset
>     raise Exception(f"Optimizer._reset({key}, {value}): missing implementation!")
> Exception: Optimizer._reset(centers, [[-1, -1, -1],
>  [-1, -1, -0.875],
>  [-1, -1, -0.75],
>  .. 4090 skipped ..,
>  [0.875, 0.875, 0.625],
>  [0.875, 0.875, 0.75],
>  [0.875, 0.875, 0.875]]): missing implementation!
> this issue trigger both in ubuntu and windows

I’m running into the exact same issue. Did you manage to find a fix? Thanks a lot!
